# Generated by Django 4.0.2 on 2022-07-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_special_special_special_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='special_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
