# Generated by Django 4.0.2 on 2022-07-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_special_special_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='special_id',
        ),
        migrations.RemoveField(
            model_name='special',
            name='special_name',
        ),
        migrations.AddField(
            model_name='special',
            name='special_id_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='special',
            name='special_id_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='special',
            name='special_id_3',
            field=models.IntegerField(default=0),
        ),
    ]
